### PR TITLE
Fix TypeError: Cannot read property of undefined in render

### PR DESCRIPTION
**Pull request by mrr000**
Fix issue #31 - adds check this.$options { methods, computed, components } before use
Update dist

### CODE REVIEW

**Comment by hunterae** [comment]
This made the errors go away for me (from the 1.6.2 upgrade) but methods are not getting proxied properly as they did in version 1.5.2

**Comment by kwaight** [comment]
https://github.com/alexjoverm/v-runtime-template/pull/33

This resolved my problems with methods not proxying.

**Comment by mrr000** [comment]
> #33
> 
> This resolved my problems with methods not proxying.

fix it

**Comment by mrr000** [comment]
> This made the errors go away for me (from the 1.6.2 upgrade) but methods are not getting proxied properly as they did in version 1.5.2

fix it

**Comment by qpitlove** [comment]
👍

**Comment by alexjoverm** [comment]
Fixed by 1.7.0

**Pull request closed without merging**
