### PR TITLE
Pass props to the template

### PR DESCRIPTION
**Pull request by wizbit**
Support passing an object to the runtime template to use as props. #22

### CODE REVIEW

**Comment by alexjoverm** [comment]
Hi @wizbit thanks a lot for the PR. Could you sync it up with the latest master? otherwise conflicts will happen

**Comment by coderpradp** [comment]
I hope this works because I really need this feature in one of my project.

**Comment by wizbit** [comment]
Rebased to master

**Comment by theianjohnson** [comment]
@alexjoverm Any chance we can get this merged in? I'm looking for almost this exact feature, but this one will do for what I'm working on.

What I'm actually looking for is to be able to scope the `<v-runtime-template>` to only props passed in, and not let it have access to parent props, data, computed, etc - essentially sandboxing it.

I'm trying to see if I can use this flow to allow users to customize their own HTML, but let that HTML have access to white-listed variables, then harness Vue's renderer for not just variable replacement, but also it's `v-if`'s and `v-for`'s.

**Comment by alexjoverm** [comment]
Fixed by 1.9.0

**Pull request closed without merging**
