### PR TITLE
Handle cases where this.$options.methods, .computed, and .components …

### PR DESCRIPTION
**Pull request by hunterae**
…are not defined

### CODE REVIEW

**Comment by moltar** [comment]
I'm getting this now:

```
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
```

**Comment by moltar** [comment]
Looks like at this line:

```
      Object.keys(methods).forEach(function (e) {if(typeof this$1.$options.methods[e]==="undefined") { passthrough.methods[e] = methods[e]; }} );

```

Probably need to do:

```
      Object.keys(methods || {})
```

On all objects.

**Comment by hunterae** [comment]
@moltar , are you saying you're getting that error with the code I submitted in this pull request?

**Comment by moltar** [comment]
Yes, I am getting the error with this PR.

**Comment by hunterae** [comment]
@moltar , I did not previously rebuild the dist scripts. I did that just now and pushed. Can you see if that fixes the problem for you.

**Comment by moltar** [comment]
That does indeed work great. Thanks!

**Comment by mithom** [comment]
any idea on when this is planned to be merged? i would need this fix, and i would hate to downgrade from nuxt 2.7 all the way to 1.5

**Comment by alexjoverm** [comment]
Fixed by 1.7.0

**Pull request closed without merging**
