### PR TITLE
Fix for methods

### PR DESCRIPTION
**Pull request by kwaight**
With latest version I was getting undefined on methods.  Not sure intention here, but this resolved my use case.

### CODE REVIEW

**Comment by Duncank** [comment]
I've got the same problem with the computed properties in one of my components. [I've applied your fix](https://github.com/Duncank/v-runtime-template/commit/567dd1a9b3c04f5d39996cfb766c9ee9412a0471#diff-31fd1c144841b101b039b3168082c68e) to that as well; can you extend your pull request for that?

**Comment by AndrejHafner** [comment]
When will this fix be merged? I'm having the same problem and would like to solve it.

**Comment by bkfox** [comment]
Regarding issue #32 (problem arises for both `computed` and `methods` at least), and take a more generic approach, we can write a function to build the passthrough object:

```javascript
const buildPassthrough = (self, source, target, attr) => {
    [self, source] = [self[attr], source[attr] || {}];
    let dest = target[attr] || {};
    for(var key of Object.keys(source))
        if(typeof self==='undefined' || typeof self[key]==='undefined')
            dest[key] = source[key];
    target[attr] = dest;
}
```
It takes the component instance as `self`, the `source` and `dest`ination objects. `attr`  is the attribute we want to synchronize on source and target objects. 

Render functions becomes:

```javascript
// if (this.template) {
      let passthrough = {};
      buildPassthrough(self, this.$parent, passthrough, '$data');
      buildPassthrough(self, this.$parent, passthrough, '$props');
      buildPassthrough(self, this.$parent, passthrough, '$options');
      buildPassthrough(self, this.$parent.$options, passthrough, 'components');
      buildPassthrough(self, this.$parent.$options, passthrough, 'computed');
      buildPassthrough(self, this.$parent.$options, passthrough, 'methods');

      // const methodKeys = Object.keys(passthrough.methods || {});
      // ...
```

**Comment by hunterae** [comment]
@kwaight , I just put in another PR that fixes the index.js file directly and is similar to your fix here (but also takes care of computed properties and components, should those also be a problem). See https://github.com/alexjoverm/v-runtime-template/pull/45. I also pinged @alexjoverm directly on Twitter just now to see if we can get a fix merged in for this since a lot of us seem to be having the same problem(s).

**Comment by alexjoverm** [comment]
Fixed by 1.7.0

**Pull request closed without merging**
