### PR TITLE
Handle existing keys from mixins/plugins

### PR DESCRIPTION
**Pull request by Pyro979**
Added some scaffolding so that I was able to test my changes as I was developing. Feel free to grab all or just the changes in index.js and re-build on your own.

### CODE REVIEW

**Comment by Pyro979** [comment]
@alexjoverm not sure if this reintroduces: Local state changes do not update runtime-template #1

Could you confirm? I'm not sure I understand that initial issue, and I'm I afraid that I did not cover that case.

**Comment by Solinx** [comment]
What is being referred to in that issue is that the dynamic component created by v-runtime copies the `data` properties of the parent component and does not maintain a reference, meaning that if the data in the parent component changes, the changes are not applied to the dynamic component.

**Comment by Solinx** [comment]
I haven't taken a close look, but I'd say your code looks good with respect to that point. This looks to be the commit where @alexjoverm made the data, etc. reactive:
https://github.com/alexjoverm/v-runtime-template/commit/18069995f19a9e16a09a1a4e5a92beb984346a61

**Comment by alexjoverm** [comment]
Hey @Pyro979 !!! All looking good!

Thanks a lot for the PR and all the work that took!

**Comment by Pyro979** [comment]
np 😄 you think it should be a minor version bump in case it causes any issues?

**Pull request closed without merging**
